// AUTO-GENERATED by tools/genDailyPuzzles.mjs — do not edit by hand.
// Each puzzle is verified solvable; solutionCount is the number of valid jar
// orderings (lower = harder). solution is one known winning move sequence.
import { Position } from './GameState';

export interface DailyPuzzle {
    board_width: number;
    board_height: number;
    start: Position;
    jars: Position[];
    solutionCount: number;
    solution: ('left' | 'right' | 'up' | 'down')[];
}

export const DAILY_PUZZLES: DailyPuzzle[] = [
    {
        "board_width": 13,
        "board_height": 13,
        "start": {
            "x": 6,
            "y": 2
        },
        "jars": [
            {
                "x": 4,
                "y": 7
            },
            {
                "x": 9,
                "y": 8
            },
            {
                "x": 2,
                "y": 4
            },
            {
                "x": 4,
                "y": 10
            },
            {
                "x": 8,
                "y": 10
            },
            {
                "x": 2,
                "y": 1
            },
            {
                "x": 4,
                "y": 1
            },
            {
                "x": 1,
                "y": 10
            },
            {
                "x": 2,
                "y": 8
            },
            {
                "x": 8,
                "y": 6
            },
            {
                "x": 9,
                "y": 6
            },
            {
                "x": 2,
                "y": 9
            },
            {
                "x": 2,
                "y": 7
            },
            {
                "x": 6,
                "y": 10
            }
        ],
        "solutionCount": 8,
        "solution": [
            "down",
            "left",
            "left",
            "right",
            "up",
            "right",
            "down",
            "left",
            "up",
            "right",
            "up",
            "left",
            "down",
            "down"
        ]
    },
    {
        "board_width": 13,
        "board_height": 13,
        "start": {
            "x": 2,
            "y": 8
        },
        "jars": [
            {
                "x": 3,
                "y": 3
            },
            {
                "x": 11,
                "y": 4
            },
            {
                "x": 7,
                "y": 1
            },
            {
                "x": 9,
                "y": 1
            },
            {
                "x": 9,
                "y": 10
            },
            {
                "x": 4,
                "y": 3
            },
            {
                "x": 7,
                "y": 3
            },
            {
                "x": 4,
                "y": 5
            },
            {
                "x": 4,
                "y": 1
            },
            {
                "x": 2,
                "y": 9
            },
            {
                "x": 2,
                "y": 5
            },
            {
                "x": 9,
                "y": 3
            },
            {
                "x": 3,
                "y": 4
            },
            {
                "x": 3,
                "y": 1
            }
        ],
        "solutionCount": 5,
        "solution": [
            "down",
            "up",
            "right",
            "up",
            "left",
            "right",
            "right",
            "down",
            "up",
            "left",
            "left",
            "left",
            "down",
            "right"
        ]
    },
    {
        "board_width": 13,
        "board_height": 13,
        "start": {
            "x": 5,
            "y": 10
        },
        "jars": [
            {
                "x": 3,
                "y": 7
            },
            {
                "x": 3,
                "y": 6
            },
            {
                "x": 8,
                "y": 6
            },
            {
                "x": 7,
                "y": 4
            },
            {
                "x": 3,
                "y": 1
            },
            {
                "x": 6,
                "y": 11
            },
            {
                "x": 6,
                "y": 1
            },
            {
                "x": 9,
                "y": 1
            },
            {
                "x": 7,
                "y": 1
            },
            {
                "x": 11,
                "y": 10
            },
            {
                "x": 11,
                "y": 4
            },
            {
                "x": 8,
                "y": 11
            },
            {
                "x": 7,
                "y": 11
            },
            {
                "x": 5,
                "y": 1
            }
        ],
        "solutionCount": 6,
        "solution": [
            "right",
            "up",
            "left",
            "up",
            "left",
            "down",
            "right",
            "right",
            "up",
            "left",
            "down",
            "up",
            "right",
            "right"
        ]
    },
    {
        "board_width": 13,
        "board_height": 13,
        "start": {
            "x": 5,
            "y": 7
        },
        "jars": [
            {
                "x": 9,
                "y": 3
            },
            {
                "x": 2,
                "y": 1
            },
            {
                "x": 6,
                "y": 11
            },
            {
                "x": 6,
                "y": 6
            },
            {
                "x": 11,
                "y": 7
            },
            {
                "x": 11,
                "y": 11
            },
            {
                "x": 6,
                "y": 9
            },
            {
                "x": 9,
                "y": 8
            },
            {
                "x": 4,
                "y": 5
            },
            {
                "x": 4,
                "y": 3
            },
            {
                "x": 6,
                "y": 7
            },
            {
                "x": 9,
                "y": 7
            },
            {
                "x": 2,
                "y": 5
            },
            {
                "x": 2,
                "y": 7
            }
        ],
        "solutionCount": 7,
        "solution": [
            "left",
            "right",
            "up",
            "down",
            "down",
            "right",
            "up",
            "left",
            "down",
            "up",
            "left",
            "down",
            "left",
            "up"
        ]
    },
    {
        "board_width": 13,
        "board_height": 13,
        "start": {
            "x": 10,
            "y": 5
        },
        "jars": [
            {
                "x": 9,
                "y": 4
            },
            {
                "x": 6,
                "y": 4
            },
            {
                "x": 10,
                "y": 6
            },
            {
                "x": 6,
                "y": 2
            },
            {
                "x": 5,
                "y": 6
            },
            {
                "x": 9,
                "y": 1
            },
            {
                "x": 6,
                "y": 5
            },
            {
                "x": 5,
                "y": 1
            },
            {
                "x": 3,
                "y": 5
            },
            {
                "x": 3,
                "y": 2
            },
            {
                "x": 5,
                "y": 4
            },
            {
                "x": 10,
                "y": 4
            },
            {
                "x": 9,
                "y": 5
            },
            {
                "x": 8,
                "y": 5
            }
        ],
        "solutionCount": 37,
        "solution": [
            "left",
            "left",
            "left",
            "left",
            "up",
            "right",
            "down",
            "left",
            "right",
            "right",
            "down",
            "left",
            "up",
            "right"
        ]
    },
    {
        "board_width": 13,
        "board_height": 13,
        "start": {
            "x": 4,
            "y": 7
        },
        "jars": [
            {
                "x": 7,
                "y": 6
            },
            {
                "x": 1,
                "y": 4
            },
            {
                "x": 7,
                "y": 2
            },
            {
                "x": 8,
                "y": 4
            },
            {
                "x": 5,
                "y": 4
            },
            {
                "x": 7,
                "y": 7
            },
            {
                "x": 5,
                "y": 5
            },
            {
                "x": 8,
                "y": 10
            },
            {
                "x": 5,
                "y": 2
            },
            {
                "x": 8,
                "y": 3
            },
            {
                "x": 7,
                "y": 10
            },
            {
                "x": 1,
                "y": 3
            },
            {
                "x": 7,
                "y": 9
            },
            {
                "x": 11,
                "y": 2
            }
        ],
        "solutionCount": 5,
        "solution": [
            "right",
            "up",
            "up",
            "down",
            "down",
            "right",
            "up",
            "up",
            "left",
            "down",
            "right",
            "down",
            "up",
            "right"
        ]
    },
    {
        "board_width": 13,
        "board_height": 13,
        "start": {
            "x": 6,
            "y": 6
        },
        "jars": [
            {
                "x": 7,
                "y": 4
            },
            {
                "x": 3,
                "y": 11
            },
            {
                "x": 3,
                "y": 4
            },
            {
                "x": 6,
                "y": 5
            },
            {
                "x": 8,
                "y": 8
            },
            {
                "x": 9,
                "y": 1
            },
            {
                "x": 6,
                "y": 1
            },
            {
                "x": 9,
                "y": 8
            },
            {
                "x": 9,
                "y": 4
            },
            {
                "x": 8,
                "y": 10
            },
            {
                "x": 6,
                "y": 11
            },
            {
                "x": 6,
                "y": 9
            },
            {
                "x": 8,
                "y": 4
            },
            {
                "x": 7,
                "y": 1
            }
        ],
        "solutionCount": 16,
        "solution": [
            "up",
            "up",
            "right",
            "right",
            "down",
            "down",
            "left",
            "down",
            "up",
            "left",
            "left",
            "down",
            "right",
            "up"
        ]
    }
];
