// Generates the curated daily puzzle set into src/utils/dailyPuzzles.ts.
// Jars are placed randomly (not chained), then a BFS/DFS solver keeps only
// layouts that are solvable, and ranks difficulty by how few of the possible
// jar orderings actually work — fewer valid orderings = harder puzzle.
// Deterministic (fixed seed): re-running reproduces the same file.
import { writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const OUT_FILE = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'utils', 'dailyPuzzles.ts');

const BOARD_WIDTH = 14;  // interior 12 cols — the original game's board size
const BOARD_HEIGHT = 14; // interior 12 rows
const JAR_COUNT = 14;
const PUZZLE_COUNT = 7;
// Difficulty band: at most this many valid complete orderings out of the 14!
// possible — fewer valid orderings = harder puzzle
const MAX_SOLUTION_COUNT = 40;

function mulberry32(seed) {
    return () => {
        seed |= 0; seed = (seed + 0x6d2b79f5) | 0;
        let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
        t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
        return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
}

const DIRS = [
    { name: 'left', dx: -1, dy: 0 },
    { name: 'right', dx: 1, dy: 0 },
    { name: 'up', dx: 0, dy: -1 },
    { name: 'down', dx: 0, dy: 1 },
];

// Slide from (x,y): returns the index of the jar landed on, or -1 (lethal wall)
function slide(x, y, dx, dy, jars, mask) {
    for (;;) {
        x += dx; y += dy;
        if (x <= 0 || x >= BOARD_WIDTH - 1 || y <= 0 || y >= BOARD_HEIGHT - 1) return -1;
        for (let j = 0; j < jars.length; j++) {
            if ((mask & (1 << j)) && jars[j].x === x && jars[j].y === y) return j;
        }
    }
}

// Solve: returns { solvable, solutionCount, oneSolution (dir names) }
function solve(start, jars) {
    const fullMask = (1 << jars.length) - 1;
    const stateKey = (x, y, mask) => (mask * BOARD_WIDTH + x) * BOARD_HEIGHT + y;

    // Count complete orderings with memoized DFS
    const countMemo = new Map();
    const CAP = MAX_SOLUTION_COUNT * 50; // cap so easy boards bail out fast
    function countPaths(x, y, mask) {
        if (mask === 0) return 1;
        const key = stateKey(x, y, mask);
        if (countMemo.has(key)) return countMemo.get(key);
        let total = 0;
        for (const d of DIRS) {
            const j = slide(x, y, d.dx, d.dy, jars, mask);
            if (j >= 0) {
                total += countPaths(jars[j].x, jars[j].y, mask & ~(1 << j));
                if (total > CAP) break;
            }
        }
        countMemo.set(key, total);
        return total;
    }

    const solutionCount = countPaths(start.x, start.y, fullMask);
    if (solutionCount === 0) return { solvable: false };

    // Extract one solution greedily via the memo (any move whose subtree has paths)
    const oneSolution = [];
    let { x, y } = start;
    let mask = fullMask;
    while (mask !== 0) {
        let moved = false;
        for (const d of DIRS) {
            const j = slide(x, y, d.dx, d.dy, jars, mask);
            if (j >= 0 && countPaths(jars[j].x, jars[j].y, mask & ~(1 << j)) > 0) {
                oneSolution.push(d.name);
                x = jars[j].x; y = jars[j].y;
                mask &= ~(1 << j);
                moved = true;
                break;
            }
        }
        if (!moved) throw new Error('inconsistent solver state');
    }

    return { solvable: true, solutionCount, oneSolution };
}

function generate() {
    const rnd = mulberry32(20260702);
    const puzzles = [];
    let attempts = 0;

    while (puzzles.length < PUZZLE_COUNT && attempts < 500000) {
        attempts++;
        const cells = new Set();
        const cell = () => ({
            x: 1 + Math.floor(rnd() * (BOARD_WIDTH - 2)),
            y: 1 + Math.floor(rnd() * (BOARD_HEIGHT - 2)),
        });
        const start = cell();
        cells.add(`${start.x},${start.y}`);
        const jars = [];
        while (jars.length < JAR_COUNT) {
            const c = cell();
            const k = `${c.x},${c.y}`;
            if (cells.has(k)) continue;
            cells.add(k);
            jars.push(c);
        }

        const result = solve(start, jars);
        if (!result.solvable) continue;
        if (result.solutionCount > MAX_SOLUTION_COUNT) continue;

        puzzles.push({ start, jars, solutionCount: result.solutionCount, solution: result.oneSolution });
        console.log(`  puzzle ${puzzles.length}: ${result.solutionCount} valid orderings (attempt ${attempts})`);
    }

    if (puzzles.length < PUZZLE_COUNT) throw new Error(`only found ${puzzles.length} puzzles`);
    return puzzles;
}

console.log('Searching for daily puzzles...');
const puzzles = generate();

const ts = `// AUTO-GENERATED by tools/genDailyPuzzles.mjs — do not edit by hand.
// Each puzzle is verified solvable; solutionCount is the number of valid jar
// orderings (lower = harder). solution is one known winning move sequence.
import { Position } from './GameState';

export interface DailyPuzzle {
    board_width: number;
    board_height: number;
    start: Position;
    jars: Position[];
    solutionCount: number;
    solution: ('left' | 'right' | 'up' | 'down')[];
}

export const DAILY_PUZZLES: DailyPuzzle[] = ${JSON.stringify(
    puzzles.map(p => ({
        board_width: BOARD_WIDTH,
        board_height: BOARD_HEIGHT,
        start: p.start,
        jars: p.jars,
        solutionCount: p.solutionCount,
        solution: p.solution,
    })), null, 4)};
`;

writeFileSync(OUT_FILE, ts);
console.log(`Wrote ${puzzles.length} puzzles to src/utils/dailyPuzzles.ts`);
